# -*- coding: utf-8 -*-
"""Stock Entry Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiwNku3Pu7pyJsHaOOkAA3xsH3aIGUG1
"""

import sys

output_file = open("output.txt", "w")
sys.stdout = output_file

import yfinance as yf
import pandas as pd

# Define watchlist
watchlist = ["WDC", "STX", "GOOGL", "AVGO", "RCL", "COST", "AMZN", 
             "MSFT", "MNST", "META", "NVDA", "TJX", "AMD", "EAT", 
             "HWM", "JNJ", "LLY", "LRCX", "MA", "MU", "TSM", "V",
             "INTC", "WMT", "AAPL"]

# Download 1 year of daily data for stocks
def get_data(ticker):
  df = yf.download(ticker, period="1y", interval="1d",auto_adjust=True,progress=False)
  df = df.dropna()
  return df

from scipy.signal import argrelextrema
import numpy as np
import pandas as pd # Ensure pandas is imported

# Detect swing lows
def get_swing_lows(df, order=3):

  # Directly access the 'Low' column assuming single-level column names
  lows = df['Low'].astype(float).values
  minima = argrelextrema(lows, np.less, order=order)[0]

  # Create a new DataFrame directly with a single 'Low' column from the minima values
  swing_lows = pd.DataFrame(df.iloc[minima]['Low'].astype(float).round(2))
  swing_lows.columns = ['Low'] # Ensure the column is explicitly named 'Low' (string)

  # Now, drop_duplicates should work correctly as 'Low' is a simple string column name.
  swing_lows = swing_lows.drop_duplicates(subset=['Low'])

  #print("Swing lows:", swing_lows)
  swing_lows = swing_lows.reset_index()
  swing_lows.columns = ['Date', 'Low']

  return swing_lows

from numpy._core.defchararray import center

# Group nearby price levels together
def cluster_supports(levels, tolerance=0.03):
  zones = []

  # Ensure levels is 1D numpy array of scalars
  levels = np.array(levels).flatten()
  levels = [float(x.item()) if isinstance(x, np.ndarray) else float(x) for x in levels]
  levels = sorted(levels)

  for level in levels:
        found_zone = False
        for zone in zones:
            center = float(zone['center'])
            if abs(level - center)/center <= tolerance:
                zone['prices'].append(level)
                zone['center'] = np.mean(zone['prices'])
                found_zone = True
                break
        if not found_zone:
            zones.append({'center': level, 'prices': [level]})

  #print("Zones after clustering:")
  #for z in zones:
        #print(z)
  return zones

# Rank support zones (Strongest first)
def rank_support_zones(zones):

  ranked = sorted(
      zones,
      key=lambda z: len(z['prices']),
      reverse=True
  )
  #print("Zones after ranking:")
  #for z in ranked:
        #print(z)

  return ranked

# Detects full support zones
def find_support_zones(df):
  swing_lows = get_swing_lows(df)
  #print("Swing lows:", swing_lows)

  if len(swing_lows) == 0:
        return []

  zones = cluster_supports(swing_lows, tolerance=0.03)
  #print("Zones after clustering:", zones)

  zones = rank_support_zones(zones)
  #print("Zones after ranking:", zones)

  return zones

# Checks if price is near support zone
def near_support_zone(price, zones, tolerance=0.03):

  for zone in zones:

    center = zone['center']
    if abs(price-center)/center <= tolerance:
      return True, center

  return False, None

# Detects rebound signals
def rebound_signal(df,support):
  last_close = df['Close'].iloc[-1].item()
  prev_close = df['Close'].iloc[-2].item()
  prev_low = df['Low'].iloc[-2].item()

  if abs(prev_low - support)/support < 0.01 and last_close > prev_close:
    return True

  return False

# Detects full support zones (Redefined here to fix the error within this cell)
def find_support_zones(df):
  swing_lows_df = get_swing_lows(df) # Renamed variable to avoid confusion

  if len(swing_lows_df) == 0:
        return []

  # Pass only the 'Low' column values to cluster_supports
  zones = cluster_supports(swing_lows_df['Low'].values, tolerance=0.03)

  zones = rank_support_zones(zones)

  return zones

# Run the signal
def check_signals(watchlist):
  signals = []
  for ticker in watchlist:
    df = get_data(ticker)
    if len(df) < 50:
        print(f"{ticker}: Not enough data")
        continue

    # This call will now use the redefined find_support_zones
    zones = find_support_zones(df)
    price = df['Close'].iloc[-1].item()
    near, support = near_support_zone(price, zones)

    if near and rebound_signal(df, support):
        decision = f"Near support at {support:.2f} – possible entry!"
        signals.append((ticker, support))
    else:
        decision = "No entry signal at the moment."

    # Always show the closest support zone
    if zones:
      closest_zone = min(zones, key=lambda z: abs(price - z['center']))
      print(f"{ticker}: {decision}")
      print(f" -> Latest close: {price:.2f}")
      print(f" -> Closest support zone: {closest_zone['center']:.2f} | Touches: {len(closest_zone['prices'])} | Distance: {abs(price - closest_zone['center'])/closest_zone['center']*100:.2f}%")
    else:
      print(f"{ticker}: No support zones found")

    # Print decision for each stock
    # print(f"{ticker}: {decision}")

  # Optional summary
  if signals:
    print("\nSummary of signals:")
    for ticker, level in signals:
        print(f"{ticker}: Signal near support at {level:.2f}")
  else:
    print("\nNo entry signals for any stock.")

check_signals(watchlist)

output_file.close()
